version: '2'

services:
        scrapyd:
                image: hehanlin/scrapyd
                ports:
                        - 6800:6800
                volumes:
                        - ./scrapyd:/var/lib/scrapyd
                restart: always
                links:
                  - splash:zc.hehanlin.cn
                  - mongodb:zz.hehanlin.cn
        splash:
                image: scrapinghub/splash
                ports:
                        - 8050:8050
                restart: always
        mongodb:
                image: mongo
                volumes:
                        - ./mongodb:/data/db
                ports:
                        - 27018:27017
                restart: always
